### ISSUE TITLE
Evaluate if the "Usability test quality heuristics" PDF is relevant to the UX Guide

### ISSUE THREAD

**Issue by nickttng** [18F/ux-guide#221]
**Background context:** In a [Slack convo](https://gsa-tts.slack.com/archives/CDDLUQ694/p1597263935002500)🔒 ,  @Jacklynn prompted a question about recreating the PDF table into a HTML/Markdown table, so that she (and others) can share a link to the _Usability test quality heuristics_ instead of a PDF version (attached in the Slack convo)

**Questions we might have about this suggestion:**

- Is the PDF content relevant to the UX Guide? Or how might this be adapted to the guide?
- How would the table content be maintained? Who is maintaining the original PDF source? Should the HTML/Markdown table be updated whenever the PDF is updated?

**Reviewers:** 

- @jstrothman (Interim PO) - To evaluate and prioritize
- @Jacklynn - The requestor

**Comment by Jacklynn** [comment]
Hello, you are all wonderful, I searched harder and found it on the website already in [the resources page](https://ux-guide.18f.gov/resources/ ) but it's [an internal google doc](https://docs.google.com/document/d/1qfGp3H1pdOlNbMYuJNQGyBIkpOcQErduDAl0adv1X-w/edit), which is why I wasn't able to find it before...so maybe the question is would want to make it public or is there a risk?

**Comment by jstrothman** [comment]
We currently share the heuristics with partners, so lets go ahead and create a public markdown version of the heuristics guide in the Resources folder.

**Comment by aditirao** [comment]
hi @nickttng and @jstrothman, in determining how best to add this page to the [Resources](https://ux-guide.18f.gov/resources/) section so that it's consistent with the rest of the content, i figured i'd add it as a link within the [Research](https://ux-guide.18f.gov/resources/#research) section. 

in reviewing the links there, i noticed that they all lead to the... hopefully i'm stating this correctly — the ".md" or markdown version of the file, rather than the webpage generated from that. eg. "Research plan" links to https://github.com/18F/ux-guide/blob/master/_pages/resources/research-plan.md, when it could instead link to https://ux-guide.18f.gov/resources/research-plan/. 

is there a particular reason for why these links are done in this way? i'd have thought we'd be linking to the HTML page since that's the point of the markdown.

**Comment by aditirao** [comment]
I've created the [public markdown version of the heuristics guide](https://github.com/18F/ux-guide/blob/master/_pages/resources/usability-test-quality-heuristics.md), and listed and linked it and its [Gdoc version](https://docs.google.com/document/d/1qfGp3H1pdOlNbMYuJNQGyBIkpOcQErduDAl0adv1X-w/edit) in the [Resources - Research](https://ux-guide.18f.gov/resources/#research) section, as well as added a short description. i also removed it from the General list further below on the page.  @jstrothman this is ready for your review. thanks!
