### ISSUE TITLE
Determine how UX guide connects to the TTS Handbook Research page

### ISSUE THREAD

**Issue by NorahMaki** [18F/ux-guide#36]

**Comment by MelissaBraxton** [comment]
Pages to audit

- https://handbook.tts.gsa.gov/research-guidelines/
- https://handbook.tts.gsa.gov/design/
- https://methods.18f.gov/
- https://handbook.tts.gsa.gov/working-groups-and-guilds-101/
- https://digital.gov/topics/research/
- https://digital.gov/communities/user-experience/

**Comment by lauraponce** [comment]
Starting with the Methods first since that feels a little separate from the other pages.

### Linking to the Methods from the Guide
I think a good way to connect the two together would be adding references in the "Additional reading" section at the end of the UX Guide pages for Plan, Do, Make research actionable, and Privacy to the Method cards. Thoughts on this, @jstrothman? 

For example here's with a link to the Methods added in the additional reading section: 

<img width="1009" alt="Screen Shot 2021-01-22 at 3 58 28 PM" src="https://user-images.githubusercontent.com/21222704/105561100-b84aef80-5cca-11eb-9a18-0d4f4ad43a66.png">

### Linking to the Guide from the Methods
And similarly, the Method cards have an "Additional resources" section for some of the cards that we could link over to the Guide for where it makes sense (e.g. Privacy). It may be a question for the Methods team to consider how much more they want to point people to the UX Guide, it could even be something more prominent like a plug at the bottom of the page? This is a super quick mockup so not this _exactly_, but I could picture something along these lines (see the end of the page): 

![methods cards with ux guide plug](https://user-images.githubusercontent.com/21222704/105560693-66ee3080-5cc9-11eb-9ff9-c0f6b66696d6.png)

**Comment by lauraponce** [comment]
After reviewing the three related Handbook pages, here's what I think makes sense for connecting the Handbook to the UX Guide:

### 1. [Working groups and guilds](https://handbook.tts.gsa.gov/working-groups-and-guilds-101/)
- No change needed — this page is focused on just the guilds and working groups, and there's no mention of any guides

### 2. [Design](https://handbook.tts.gsa.gov/design/)
- Add a UX Guide link to the Documentation section
- Change the link in the Tools > Research section (first bullet) from https://handbook.tts.gsa.gov/research-guidelines to the UX Guide instead

### 3. [Research guidelines](https://handbook.tts.gsa.gov/research-guidelines/)
- Archive this page
- Update the UX Guide to incorporate anything here that isn't already in the Guide (from what I can tell, it seems to overlap very much with the UX Guide, but this page does have everything in one place whereas the UX Guide is more scattered)
- Update all links to this page to point to the UX Guide instead

**Comment by lauraponce** [comment]
For Digital.gov:

### [Research page](https://digital.gov/topics/research/)
- Update the first bullet point for resources to go to the UX Guide instead of the Handbook page and update the corresponding text to: "A comprehensive guide for conducting ethical user research in government and includes resources such as templates and checklists."
 
### [User experience community](https://digital.gov/communities/user-experience/)
- Add a bullet point in the `Key resources` section with a link to the UX Guide

**Comment by lauraponce** [comment]
@jstrothman what are your thoughts on these suggestions for connecting the UX Guide to the Methods, Handbook, and Digital.gov?

**Comment by lauraponce** [comment]
I was just taking the customer experience OLU course and they direct people to these resources at the end:
 
![Screen Shot 2021-01-27 at 10 27 34 AM](https://user-images.githubusercontent.com/21222704/106036521-4daf0080-608a-11eb-8117-a594fc207c48.png)
I think this is meant to be for the office of customer experience so we probably don't need to link to the Guide in the training, but the second bullet point for the [Customer Experience Toolkit](https://digital.gov/resources/customer-experience-toolkit/) page actually has the perfect place we could add a link — as a list item in the Design > "Follow design best practices section": 

![Screen Shot 2021-01-27 at 10 31 18 AM](https://user-images.githubusercontent.com/21222704/106036944-d75ece00-608a-11eb-96c4-5f253b2a04fb.png)
